version: "3.9"

services:
  Mongo1:
    container_name: Mongo1
    image: mongo:5
    networks:
      - mongo-replica-set
    ports:
      - "27017:27017"
    command: mongod --replSet myReplicaSet --bind_ip localhost,Mongo1

  Mongo2:
    container_name: Mongo2
    image: mongo:5
    networks:
      - mongo-replica-set
    ports:
      - "27018:27017"
    command: mongod --replSet myReplicaSet --bind_ip localhost,Mongo2

  Mongo3:
    container_name: Mongo3
    image: mongo:5
    networks:
      - mongo-replica-set
    ports:
      - "27019:27017"
    command: mongod --replSet myReplicaSet --bind_ip localhost,Mongo3

  mongo-init:
    image: mongo:5
    container_name: mongo_init
    depends_on:
      - Mongo1
      - Mongo2
      - Mongo3
    networks:
      - mongo-replica-set
    entrypoint: >
      bash -c "sleep 10 && 
      mongosh --host Mongo1:27017 --eval 'rs.initiate({
        _id: \"myReplicaSet\",
        members: [
          { _id: 0, host: \"Mongo1:27017\" },
          { _id: 1, host: \"Mongo2:27017\" },
          { _id: 2, host: \"Mongo3:27017\" }
        ]
      })'"

  yolo5:
    container_name: yolo5
    image: ${YOLO5_IMG_NAME}
    environment:
      BUCKET_NAME: ${S3_BUCKET_NAME}
    ports:
      - "8081:8081"
    networks:
      - mongo-replica-set
    depends_on:
      - Mongo1
      - Mongo2
      - Mongo3

  polybot:
    container_name: polybot
    image: ${POLYBOT_IMG_NAME}
    environment:
      TELEGRAM_TOKEN: ${POLYBOT_IMG_NAME}
      TELEGRAM_APP_URL: ${TELEGRAM_APP_URL}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION}
    ports:
      - "8443:8443"
    networks:
      - mongo-replica-set
    depends_on:
      - yolo5

networks:
  mongo-replica-set:
    driver: bridge
